server:
  port: 8082
  tomcat:
    accesslog:
      directory: /dev/stdout
      enabled: true
      pattern: "%m %U %s %Dms MDC:[%I] Session:[%{X-Session-ID}i]"
logging:
    level:
        root: INFO
        com.changeowl: INFO
        org.springframework.web: INFO
        org.springframework.web.servlet.DispatcherServlet: INFO
spring:
  application:
    name: storage-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
changeowl:
  agent-service:
    url: ${AGENT_SERVICE_URL:http://localhost:8052}
semantic:
  service:
    url: ${SEMANTIC_SERVICE_API_URL}
    api-key: ${SEMANTIC_SERVICE_API_KEY}