server:
  port: 8082
logging:
  level:
    root: DEBUG
    com.changeowl: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://localhost:5432/changeowl
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
semantic:
  service:
    url: http://localhost:8050
    api-key: ytrBAvEmm4nfceCNl7Jymfk4aztMpyGs
